version: 2
project_name: speedtest

before:
  hooks:
    - go mod tidy

builds:
  - id: speedtest
    main: ./main.go
    binary: speedtest
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: speedtest
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  github:
    owner: chancelyg
    name: speedtest-go
  # Automatically mark releases with pre-release suffixes
  # (e.g. v0.0.1-alpha) as GitHub pre-releases.
  prerelease: auto
  name_template: '{{.ProjectName}} {{.Tag}}'

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"
